In [1]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [7]:
arr=np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [10]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [12]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [22]:
#zeros returns 0s
# 2 is the number of rows and 3 is the number of columns
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
#ones return 1s
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
## linspace
# third arguement is not number of evenly spaced points
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
#eye for identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(5)

array([0.11952596, 0.37848499, 0.22574551, 0.12372782, 0.54838618])

In [26]:
np.random.rand(5,5)

array([[0.24939744, 0.45985742, 0.04290608, 0.15512082, 0.49234658],
       [0.10941332, 0.14052046, 0.14778107, 0.27142674, 0.51116074],
       [0.26381077, 0.73797757, 0.51825767, 0.20312309, 0.12515207],
       [0.87688867, 0.9133578 , 0.37609914, 0.13136913, 0.60077443],
       [0.94107427, 0.53808893, 0.13393445, 0.28247132, 0.40724961]])

In [34]:
np.random.randn(2)

array([-1.08122839,  1.45831753])

In [36]:
#(1,100) is just as same as in range
np.random.randint(1,100)

40

In [39]:
#third arguement - number of randoms
np.random.randint(1,100,10)

array([13, 24,  6, 84,  1, 62, 65, 52, 31, 65])

In [44]:
arr=np.arange(25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [45]:
#reshaping an array to square matrix
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr=np.random.randint(0,50,10)
print(ranarr)

[14 44  4 46 23 30 14 21  1 39]


In [48]:
ranarr.max()

46

In [49]:
ranarr.min()

1

In [51]:
#index of max
ranarr.argmax()

3

In [53]:
#index of min
ranarr.argmin()

8

In [55]:
#returns the shape- one element means it is a one dimentional array and
arr.shape

(25,)

In [56]:
rearr=arr.reshape(5,5)

In [57]:
rearr.shape

(5, 5)

In [58]:
arr.dtype

dtype('int32')

In [59]:
from numpy.random import randint

In [60]:
randint(2,10)

9