In [1]:
import numpy as np

In [2]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [4]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [6]:
#row as arguement
arr_2d[0]

array([ 5, 10, 15])

In [9]:
#
#row & column as arguement....just as same as python indexing
arr_2d[0][0]

5

In [12]:
#indexing with single bracket notation
#[row,column]
arr_2d[1,1]

25

In [13]:
#slicing a two dimensional array
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [14]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [15]:
#conditional selection
arrOne=np.arange(1,11)
arrOne

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
#condition
bool_arrOne=arrOne>5
bool_arrOne

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [21]:
#conditonal selection
arrOne[bool_arrOne]

array([ 6,  7,  8,  9, 10])

In [23]:
arrOne[arrOne>8]

array([ 9, 10])

In [24]:
arrOne[arrOne<3]

array([1, 2])

In [26]:
arr2dTwo=np.arange(50).reshape(5,10)
arr2dTwo

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [28]:
#grabbing 13,14,23,24
arr2dTwo[1:3,3:5]

array([[13, 14],
       [23, 24]])